; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-c3]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
board_build.filesystem = littlefs
upload_port = /dev/cu.usbserial-2110
monitor_port = /dev/cu.usbserial-2110
monitor_speed = 115200
monitor_raw = yes
build_flags =
  -DDEBUG_SERIAL=Serial
  -DCORE_DEBUG_LEVEL=0
  -Iinclude
lib_deps =
  knolleary/PubSubClient @ ^2.8
  bblanchon/ArduinoJson @ ^6.21.3
  densaugeo/base64 @ ^1.4.0
  https://github.com/jnthas/Improv-WiFi-Library.git
